name: "OpenWrt packages new version check"
description: "A tool to check a new version of a package in OpenWrt"
author: ekkog
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Check
      shell: bash
      run: check.sh