name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - name: Check
      shell: bash
      run: |
        if [ -z $MAKEFILE ]; then
          MAKEFILE=Makefile
        fi

        current_version=$(cat $MAKEFILE | grep PKG_VERSION | head -n 1 | cut -d "=" -f 2)
        echo "Current version: $current_version"

        url="https://api.github.com/repos/$REPO/releases/latest"
        if [ -z $INCLUDE_PRE_RELEASE ]; then
          url="https://api.github.com/repos/$REPO/releases?per_page=1"
        fi
        latest_version=$(curl -s "$url" | jq -r '.[0].tag_name')
        echo "Latest version: $latest_version"

        if [ "$current_version" = "$latest_version" ]; then
            echo "No update"
            exit 0
        else
            wget https://github.com/$REPO/archive/refs/tags/$latest_version.tar.gz -O output.tar.gz
            hash=$(sha256sum output.tar.gz | cut -d " " -f 1)
            echo "New hash: $hash"
            sed -i "s/PKG_HASH:=.*/PKG_HASH:=$hash/g" $MAKEFILE
            rm output.tar.gz

            echo "Update to $latest_version"
            sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$latest_version/g" $MAKEFILE
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=1/g" $MAKEFILE
        fi

        git config user.name "bot"
        git config user.email "bot@github.com"
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d) Bump $REPO to $latest_version"
        if [ -z $BRANCH ]; then
          BRANCH=main
        fi
        git push "https://x-access-token:$COMMIT_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH